name: PR Review Comment
on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            👋 @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have followed our contributing guidelines in `DEVELOPER.md`. We will review it as soon as possible!

            Reviewer: Please verify the following things have been done, if applicable.
            - [ ] A file has been added to `changelog.d/`
            - [ ] "Configuration > Available options" section in `README.md` has been updated
            - [ ] "Configuration > Specifying configuration" section in `README.md` has been updated
            - [ ] Tests have been added
